version: "3"
services:
  frontend:
    image: songskipper/frontend:0.0.1-SNAPSHOT
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NGINX_PORT=80
      - SONGSKIPPER_BACKEND=http://backend:8080

  backend:
    image: songskipper/backend:0.0.1-SNAPSHOT
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/songskipper
      - SPRING_DATASOURCE_USERNAME=songskipper
      - SPRING_DATASOURCE_PASSWORD=changeit
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_USER=songskipper
      - POSTGRES_DB=songskipper
    volumes:
      - "./db_data:/var/lib/postgresql/data"