version: "3"
services:
  frontend:
    image: songskipper/frontend:0.0.1-SNAPSHOT
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NGINX_PORT=80
      - SONGSKIPPER_BACKEND=http://backend:8080

  backend:
    image: songskipper/backend:0.0.1-SNAPSHOT
