spring:
  profiles.include: secrets
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          spotify:
            #client-id: <see application-secrets.yml>
            #client-secret: <see application-secrets.yml>
            authorization-grant-type: authorization_code
            scope: user-read-private, user-read-email, user-top-read
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: basic
            authentication-scheme: query
            client-authentication-scheme: form
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token
            authorization-uri: https://accounts.spotify.com/authorize
            user-info-uri: https://api.spotify.com/v1/me
            userNameAttribute: email