spring:
  h2.console:
    enabled: true
    path: /h2
    settings.trace: true
    settings.web-allow-others: true

  jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./build/songskipper_test_db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
#logging:
#  level.root: DEBUG