spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: 0ff330610bb0419699a28abbfa9943a9
            client-secret: e4843f91d90542b6ada60b6644d52058