
filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

setup.kibana:
  host: "kibana:5601"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - contains:
            container.image.name: docker.elastic.co
    - index: "filebeat-songskipper-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - contains:
            container.image.name: songskipper
        - contains:
            container.image.name: postgresql
logging.json: true
logging.metrics.enabled: false

#filebeat.autodiscover:
#  providers:
#    - type: docker
#       templates:
#         - condition:
#             contains:
#               docker.container.image: songskipper
#           config:
#             - type: container
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log
#              #exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines